- name: Add ssh pair for root user
  ansible.builtin.user:
    name: root
    generate_ssh_key: true

- name: Fetch ssh key
  ansible.builtin.command: "cat /root/.ssh/id_rsa.pub"
  register: sshkey

- name: Put sshpubkey on backup server
  ansible.posix.authorized_key:
    user: borg
    key: "{{ sshkey.stdout }}"
  delegate_to: backup

- name: Create known_hosts file
  ansible.builtin.file:
    path: /root/.ssh/known_hosts
    state: touch
    mode: '0600'
    owner: root
    group: root
  
- name: Write the backup server's host key to known hosts
  shell: 'ssh-keyscan -H {{ backup_ip }} >> /root/.ssh/known_hosts'

- name: Create rsyslog config file for borg
  ansible.builtin.copy:
    src: borg.conf
    dest: /etc/rsyslog.d/borg.conf      

- name: Restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted

- name: Create backup log file
  file:
    path: /var/log/borg.log
    state: touch

- name: Initialize borg repo
  ansible.builtin.shell: borg init --encryption=repokey {{ backup_user }}@{{ backup_ip }}:/var/borg/backup/
  environment:
    BORG_PASSPHRASE: otus

- name: Configure borg backup service
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/systemd/system
  loop:
    - borg-backup.service
    - borg-backup.timer

- name: Start borg backup timer
  ansible.builtin.systemd:
    name: borg-backup.timer
    enabled: true
    state: started

- name: Start borg backup service
  ansible.builtin.systemd:
    name: borg-backup.service
    state: started
