- name: Add user borg
  ansible.builtin.user:
    name: borg
    password: borg

- name: Create ssh directory
  ansible.builtin.file:
    path: /home/borg/.ssh
    state: directory
    mode: '0700'
    owner: borg
    group: borg

- name: Create a file for authorized ssh keys
  ansible.builtin.file:
    path: /home/borg/.ssh/authorized_keys
    state: touch
    mode: '0600'
    owner: borg
    group: borg

- name: Create a backup directory
  ansible.builtin.file:
    path: /var/borg
    state: directory

- name: Select disk name
  shell: if [[ $(lsblk | grep sda) ]]; then echo 'sdb'; else echo 'sda'; fi
  register: backup_disk

- name: Create a ext4 filesystem on backup disc
  community.general.filesystem:
    fstype: ext4
    dev: '/dev/{{ backup_disk.stdout }}'

- name: Mount the backup directory
  ansible.posix.mount:
    src: '/dev/{{ backup_disk.stdout }}'
    path: /var/borg/backup
    boot: true
    state: mounted
    fstype: ext4

- name: Create a backup directory
  ansible.builtin.file:
    path: /var/borg/backup
    state: directory
    mode: '0700'
    owner: borg
    group: borg

- name: Clear backup directory
  shell: rm -rf /var/borg/backup/*